package com.jhchang.simplesudoku;

import android.graphics.Color;

import java.util.ArrayList;

public class Values {



    private final int smallFont = 32;
    private final int medFont = 64;
    private final int boardFont = 72;
    private final int bigFont = 100;

    private final int posTop = 0;
    private final int posTopMid = 1;
    private final int posMid = 2;
    private final int posBotMid = 3;
    private final int posBot = 4;

    private final int fasterText = 1;
    private final int fastText = 3;
    private final int normText = 12;
    private final int slowText = 20;

    private final int EASY_BOARD = 0;
    private final int MED_BOARD = 1;
    private final int HARD_BOARD = 2;

    private final int HIGHLIGHT_COLOR = Color.argb(255,51,98,191);
    private final int NEIGHBOR_COLOR = Color.argb(255,80,80,80);
    private final int FIXED_COLOR = Color.argb(255,24,24,24);
    private final int REGULAR_COLOR = Color.argb(255,40,40,40);
    private final int ERROR_COLOR = Color.argb(255,173,24,24);

    private final int BG_COLOR = Color.argb(255, 0,0,0);
    private final int FONT_COLOR = Color.argb(255, 220,220,220);
    private final int SELECT_COLOR = Color.argb(255,51,98,191);

    private final ArrayList<Board> wordNine = new ArrayList<Board>();
    private final ArrayList<Board> wordFour = new ArrayList<Board>();

    public Values(){

        initWordNine();
        initWordFour();

    }

    private void initWordNine(){
        String[][] nineList = {
                {"tribunals","noun","a court or forum of justice"},
                {"diplomacy","noun","the art and practice of conducting negotiations between nations"},
                {"hangovers","noun","something (such as a surviving custom) that remains from what is past"},
                {"playtimes","noun","a time for play or diversion"},
                {"cohabited","verb","to live together as a married couple or in the manner of a married couple"},
                {"latchkeys","noun","a key to an outside and especially a front door"},
                {"bunkmates","noun","a person occupying the same sleeping quarters as another"},
                {"importune","verb","to press or urge with troublesome persistence"},
                {"horseback","noun","the back of a horse"},
                {"desirably","adjective","having pleasing qualities or properties : attractive"},
                {"colanders","noun","a perforated utensil for washing or draining food"},
                {"cornfield","noun","a field in which corn is grown"},
                {"hydraulic","adjective","operated, moved, or effected by means of water"},
                {"osculated","verb","kiss"},
                {"dishwater","noun","water in which dishes have been or are to be washed"},
                {"lymphatic","adjective","of, relating to, or produced by lymph, lymphoid tissue, or lymphocytes"},
                {"moustache","noun","the hair growing on the human upper lip"},
                {"syncopate","verb","to cut short : clip, abbreviate"},
                {"cupboards","noun","a closet with shelves where dishes, utensils, or food is kept"},
                {"deviously","adjective","wandering, roundabout"},
                {"endurably","adjective","capable of being endured: bearable"},
                {"crimsoned","noun","any of several deep purplish reds"},
                {"cabriolet","noun","a light 2-wheeled one-horse carriage with a folding leather hood"},
                {"inoculate","verb","to introduce (something, such as a micro-organism) into a suitable situation for growth"},
                {"humanised","verb","to represent as human: attribute human qualities to"},
                {"outplayed","verb","to play better than"},
                {"champions","noun","warrior, fighter"},
                {"atrophied","noun","arrested development or loss of the normal development"},
                {"masculine","adjective","male"},
                {"furbelows","noun","a pleated or gathered piece of material"},
                {"combiners","verb","to bring into such close relationship as to obscure individual characters : merge"},
                {"backslide","verb","to lapse morally or in the practice of religion"},
                {"imposture","noun","the act or practice of deceiving by means of an assumed character or name"},
                {"tenacious","adjective","not easily pulled apart : cohesive"},
                {"dragonfly","noun","any of a suborder (Anisoptera) of odonate insects"},
                {"chagrined","noun","disquietude or distress of mind caused by humiliation, disappointment, or failure"},
                {"painterly","adjective","of, relating to, or typical of a painter: artistic"},
                {"equivocal","adjective","of uncertain disposition toward a person or thing : undecided"},
                {"hailstone","noun","a pellet of hail"},
                {"downplays","verb","play down, de-emphasize"},
                {"facetious","adjective","joking or jesting often inappropriately : waggish"},
                {"landforms","noun","a natural feature of a land surface"},
                {"nourished","verb","nurture, rear"},
                {"packhorse","noun","a horse used as a pack animal"},
                {"launchers","noun","one that launches: such as"},
                {"grouchily","adjective","given to grumbling : peevish"},
                {"irksomely","adjective","tending to irk : tedious"},
                {"procaines","noun","a basic ester C13H20N2O2of para-aminobenzoic acid"},
                {"convexity","noun","the quality or state of being convex"},
                {"schnauzer","noun","a dog of any of three breeds that originated in Germany"},
                {"extrusion","noun","the act or process of extruding"},
                {"columbine","noun","any of a genus (Aquilegia) of plants of the buttercup family"},
                {"flounders","noun","flatfish"},
                {"walkovers","noun","a one-sided contest : an easy or uncontested victory"},
                {"fruitcake","noun","a rich cake containing nuts, dried or candied fruits, and spices"},
                {"companies","noun","association with another : fellowship"},
                {"pachyderm","noun","any of various non-ruminant mammals"},
                {"laundries","noun","a room for doing the family wash"},
                {"feudatory","adjective","owing feudal allegiance"},
                {"tinderbox","noun","a metal box for holding tinder and usually a flint and steel for striking a spark"},
                {"mandibles","noun","jaw sense"},
                {"companied","noun","association with another : fellowship"},
                {"guardsmen","noun","a member of a military body called guard or guards"},
                {"farmhouse","noun","a dwelling on a farm"},
                {"bimonthly","adjective","occurring every two months"},
                {"cilantros","noun","leaves of coriander used as a flavoring or garnish"},
                {"angleworm","noun","earthworm"},
                {"educators","noun","one skilled in teaching : teacher"},
                {"blasphemy","noun","irreverence toward something considered sacred or inviolable"},
                {"breakouts","noun","a violent or forceful break from a restraining condition or situation"},
                {"husbander","noun","the manager of another's property : steward"},
                {"longitude","noun","angular distance measured on a great circle of reference"},
                {"guidances","noun","the act or process of guiding"},
                {"subaltern","adjective","subordinate"},
                {"copulated","verb","to engage in sexual intercourse"},
                {"frumpiest","adjective","dowdy, drab"},
                {"contrails","noun","streaks of condensed water vapor created in the air by an air-plane or rocket at high altitudes"},
                {"quantizes","verb","to subdivide (something, such as energy) into small but measurable increments"},
                {"randomize","verb","to select, assign, or arrange in a random-way"},
                {"requitals","noun","something given in return, compensation, or retaliation"},
                {"unreality","noun","the quality or state of being unreal: lack of substance or validity"},
                {"clipboard","noun","a small writing board with a clip at the top for holding papers"},
                {"vehicular","adjective","of, relating to, or designed for vehicles and especially motor vehicles"},
                {"copulates","verb","to engage in sexual intercourse"},
                {"frightens","verb","to make afraid : terrify"},
                {"hobnailed","noun","a short large-headed nail for studding shoe soles"},
                {"morphines","noun","a bitter crystalline addictive narcotic base; an analgesic and sedative"},
                {"compilers","noun","one that compiles"},
                {"labyrinth","noun","a maze (as in a garden) formed by paths separated by high hedges"},
                {"legations","noun","the sending forth of a legate"},
                {"larcenous","adjective","having the character of or constituting larceny"},
                {"bearishly","adjective","pessimistic"},
                {"oligarchs","noun","a member or supporter of an oligarchy"},
                {"exudation","noun","the process of exuding"},
                {"certainly","adverb","in a manner that is certain: with certainty"},
                {"knavishly","adjective","of, relating to, or characteristic of a knave"},
                {"quagmires","noun","soft miry land that shakes or yields under the foot"},
                {"sforzandi","adjective or adverb","an accented tone or chord"},
                {"auctioned","noun","a sale of property to the highest bidder"},
                {"splintery","noun","a thin piece split or broken off lengthwise : sliver"},
                {"brawniest","adjective","muscular"},
                {"implanted","verb","to set permanently in the consciousness or habit patterns : inculcate"},
                {"equations","noun","the act or process of equating"},
                {"proclaims","verb","to declare publicly, typically insistently, proudly, or defiantly"},
                {"fluorides","noun","a compound of fluorine"},
                {"chlorides","noun","a compound of chlorine with another element or group"},
                {"hideously","adjective","morally offensive : shocking"},
                {"alchemist","noun","a person who studies or practices alchemy"},
                {"culminate","verb","to be directly overhead"},
                {"womanlier","adjective","having qualities generally associated with a woman"},
                {"expulsion","noun","the act of expelling : the state of being expelled"},
                {"clumpiest","noun","a compact mass"},
                {"marigolds","noun","pot marigold"},
                {"personify","verb","to conceive of or represent as a person or as having human qualities or powers"},
                {"buckwheat","noun","any of a genus (Fagopyrumof the family Polygonaceae, the buckwheat family)"},
                {"platforms","noun","plan, design"},
                {"provident","adjective","making provision for the future : prudent"},
                {"broughams","noun","a light closed horse-drawn carriage with the driver outside in front"},
                {"absoluter","adjective","free from imperfection : perfect"},
                {"emulation","noun","ambitious or envious rivalry"},
                {"authorize","verb","to invest especially with legal authority : empower"},
                {"rheumatic","adjective","of, relating to, characteristic of, or affected with rheumatism"},
                {"modulates","verb","to tune to a key or pitch"},
                {"miscreant","adjective","unbelieving, heretical"},
                {"dipterous","adjective","of, relating to, or being a fly"},
                {"obstinacy","noun","the quality or state of being obstinate: stubbornness"},
                {"maligners","noun","one that maligns"},
                {"jointedly","noun","node sense"},
                {"privately","adjective","being educated by independent study or a tutor or in a private school "},
                {"loquacity","noun","the quality or state of being very talkative"},
                {"underflow","noun","a flowing under: movement of water through subsurface material"},
                {"liveryman","noun","a freeman of the City of London entitled to wear the livery of the company to which he belongs"},
                {"baroquely","adjective","the baroque style or the period in which it flourished"},
                {"outfields","noun","the part of a baseball field beyond the infield and between the foul lines"},
                {"impotency","noun","impotence"},
                {"perfusion","verb","suffuse"},
                {"harlequin","noun","a character in comedy and pantomime"},
                {"touchable","verb","to commit violence upon "},
                {"vulgarity","noun","something vulgar"},
                {"swordtail","noun","a small brightly marked Central American live-bearer"},
                {"blockader","verb","to subject to a blockade"},
                {"blockades","verb","to subject to a blockade"},
                {"duplicate","adjective","to make double or twofold"},
                {"ghostlier","adjective","of or relating to the soul : spiritual"},
                {"quickstep","noun","a spirited march tune usually accompanying a march in quick-time"},
                {"yachtsmen","noun","a person who owns or sails a yacht"},
                {"comradely","noun","an intimate friend or associate : companion"},
                {"poultries","noun","domesticated birds kept for eggs or meat"},
                {"penlights","noun","a small flash-light resembling a fountain pen in size or shape"},
                {"purgative","adjective","purging or tending to purge"},
                {"fractions","noun","a numerical representation indicating the quotient of two numbers"},
                {"underplay","verb","to play a role with subdued force"},
                {"drinkable","adjective","suitable or safe for drinking"},
                {"peculiars","adjective","characteristic of only one person, group, or thing : distinctive"},
                {"formality","noun","compliance with formal or conventional rules : ceremony"},
                {"physicked","noun","the art or practice of healing disease"},
                {"bungalows","noun","a one-storied house with a low-pitched roof"},
                {"benchmark","noun","a point of reference from which measurements may be made"},
                {"euphorias","noun","a feeling of well-being or elation"},
                {"adjustive","verb","to bring to a more satisfactory state:"},
                {"forsythia","noun","any of a genus (Forsythia) of ornamental shrubs of the olive family"},
                {"pectorals","noun","something worn on the breast"},
                {"hailstorm","noun","a storm accompanied by hail"},
                {"puckishly","adjective","impish, whimsical"},
                {"enviously","adjective","emulous"},
                {"factories","noun","a building or set of buildings with facilities for manufacturing"},
                {"normative","adjective","prescribing"},
                {"bungholes","noun","a hole for emptying or filling a cask"},
                {"overbuild","verb","to build beyond the actual demand of"},
                {"verticals","adjective","perpendicular to the plane of the horizon or to a primary axis : upright"},
                {"corpulent","adjective","having a large bulky body : obese"},
                {"husbandly","noun","the manager of another's property : steward"},
                {"inexactly","adjective","not precisely correct or true : inaccurate"},
                {"goatherds","noun","a person who tends goats"},
                {"inculpate","verb","to impute guilt to : incriminate"},
                {"chelation","noun","the process of chelating or the quality or state of being chelated"},
                {"pluckiest","adjective","spirited, brave"},
                {"leapfrogs","noun","a game in which one player bends down and is vaulted over by another player"},
                {"archfiend","noun","a chief fiend"},
                {"vexatious","adjective","causing vexation: distressing"},
                {"lubricant","noun","a substance capable of reducing friction, heat, and wear"},
                {"excursion","noun","a going out or forth : expedition"},
                {"baritones","noun","a male singing voice of medium compass between bass and tenor"},
                {"boldfaces","noun","a heavy-faced type"},
                {"uncharged","adjective","not charged"},
                {"quantized","verb","to subdivide (something, such as energy) into small but measurable increments"},
                {"ptomaines","noun","organic bases formed by putrefactive bacteria on nitrogenous matter"},
                {"onslaught","noun","something resembling such an attack "},
                {"mailboxes","noun","a box at or near a dwelling for the occupant's mail"},
                {"stauncher","adjective","watertight, sound"},
                {"supremacy","noun","the quality or state of being supreme"},
                {"pointedly","adjective","having a point"},
                {"subregion","noun","a subdivision of a region"},
                {"purchased","verb","gain, acquire"},
                {"womanlike","adjective","womanly"},
                {"organizes","verb","to form into a coherent unity or functioning whole : integrate"},
                {"swordplay","noun","the art or skill of wielding a sword especially in fencing"},
                {"biography","noun","a usually written account of a real person's life"},
                {"normalize","verb","to make conform to or reduce to a norm or standard"},
                {"homebuilt","adjective","home-made sense"},
                {"turnpikes","noun","a road (such as an express way) for the use of which tolls are collected"},
                {"impactors","verb","to fix firmly by or as if by packing or wedging"},
                {"steroidal","noun","any of various compounds containing a 17-carbon 4-ring system"},
                {"comedians","noun","a writer of comedies"},
                {"patronize","verb","to adopt an air of condescension toward : treat haughtily or coolly"},
                {"vesicular","adjective","having the form or structure of a vesicle"},
                {"varnished","noun","a liquid preparation that forms a hard lustrous coating"},
                {"bunchiest","noun","protuberance, swelling"},
                {"odalisque","noun","a female slave"},
                {"dulcimers","noun","a stringed instrument of trapezoidal shape played with light hammers held in the hands"},
                {"foreplays","noun","erotic stimulation preceding sexual intercourse"},
                {"husbandry","noun","the care of a household"},
                {"unclothed","adjective","not clothed"},
                {"handsomer","adjective","appropriate, suitable"},
                {"adsorbent","noun","a usually solid substance that adsorbs another substance"},
                {"undershot","adjective","having the lower jaw projecting beyond the upper"},
                {"cremation","verb","to burn (as a dead body) to ashes"},
                {"mangroves","noun","any of a genus (Rhizophora, especially R. mangleof the family Rhizophoraceae)"},
                {"paintwork","noun","paint sense"},
                {"manicured","noun","manicurist"},
                {"touchline","noun","either of the lines that bound the long sides of the field of play in rugby and soccer"},
                {"clothiers","noun","one who makes or sells clothing"},
                {"emulators","noun","one that emulates"},
                {"snowfield","noun","a broad level expanse of snow"},
                {"vineyards","noun","a planting of grapevines"},
                {"absconder","verb","to depart secretly : withdraw and hide oneself"},
                {"postfixed","adjective","characterized by placement of an operator after its operand"},
                {"mendacity","noun","lie"},
                {"volcanism","noun","volcanic action or activity"},
                {"shogunate","noun","one of a line of military governors ruling Japan until the revolution of 1867–68"},
                {"cognately","adjective","related on the mother's side"},
                {"contrived","adjective","having an unnatural or false appearance or quality : artificial, labored"},
                {"pantheism","noun","a doctrine that equates God with the forces and laws of the universe"},
                {"bounciest","adjective","buoyant, exuberant"},
                {"poundages","noun","impoundment"},
                {"overnight","adverb","on the evening before"},
                {"gravitons","noun","a hypothetical particle with zero charge and rest mass"},
                {"lichenous","noun","any of several skin diseases characterized by the eruptions of flat papules"},
                {"contrives","verb","devise, plan"},
                {"unblocked","verb","to free from being blocked"},
                {"unlatched","verb","to open or loose by lifting the latch"},
                {"verminous","adjective","consisting of or being vermin: noxious"},
                {"overhauls","verb","repair"},
                {"pocketful","noun","a small bag carried by a person : purse"},
                {"furnished","verb","to provide with what is needed"},
                {"blockhead","noun","a stupid person"},
                {"nefarious","adjective","flagrantly wicked or impious : evil"},
                {"artichoke","noun","a tall Mediterranean composite herb (Cynara scolymus)"},
                {"purgation","noun","the act or result of purging"},
                {"unsighted","verb","to prevent from seeing"},
                {"anchorite","noun","a person who lives in seclusion usually for religious reasons"},
                {"rumpliest","adjective","having rumples"},
                {"playhouse","noun","theater"},
                {"mordantly","adjective","biting and caustic in thought, manner, or style : incisive"},
                {"nightwear","noun","night clothes"},
                {"polymeric","noun","a chemical compound or mixture of compounds formed by polymerization"},
                {"exclusion","noun","the act or an instance of excluding"},
                {"trifocals","adjective","having three focal lengths"},
                {"birthdays","noun","the day of a person's birth"},
                {"nostalgic","adjective","feeling or inspiring nostalgia: such as"},
                {"glycerins","noun","glycerol"},
                {"creations","noun","the act of creating"},
                {"compliers","noun","one that complies"},
                {"insulator","noun","one that insulates: such as"},
                {"fumigants","noun","a substance used in fumigating"},
                {"birdcages","noun","a cage for confining birds"},
                {"splotched","noun","spot, blotch"},
                {"bankrupts","noun","a debtor whose property is subject to bankruptcy laws"},
                {"emigrants","noun","one who emigrates"},
                {"moneybags","noun","wealth"},
                {"vocalized","verb","to give voice to : utter"},
                {"patrimony","noun","anything derived from one's father or ancestors : heritage"},
                {"planetoid","noun","a small body resembling a planet"},
                {"introduce","verb","to lead to or make known by a formal act, announcement, or recommendation: such as"},
                {"vaporizes","verb","to convert (as by the application of heat or by spraying) into vapor"},
                {"implanter","verb","to set permanently in the consciousness or habit patterns : inculcate"},
                {"sphincter","noun","an annular muscle surrounding and able to contract or close a bodily opening"},
                {"bronchial","adjective","of or relating to the bronchi or their ramifications in the lungs"},
                {"courtship","noun","the act, process, or period of courting"},
                {"downright","adverb","straight down"},
                {"ectoplasm","noun","the outer relatively rigid granule-free layer of the cytoplasm"},
                {"handiwork","noun","work done by the hands"},
                {"megabucks","noun","one million dollars"},
                {"republish","verb","to publish again or anew"},
                {"truckload","noun","a load or amount that fills or could fill a truck"},
                {"keyboards","noun","a bank of pressable keys or buttons"},
                {"handwrite","verb","to write by hand"},
                {"syndicate","noun","a council or body of syndics"},
                {"magnitude","noun","spatial quality : size"},
                {"fisherman","noun","one who engages in fishing as an occupation or for pleasure"},
                {"tangibles","adjective","capable of being perceived especially by the sense of touch : palpable"},
                {"profusely","adjective","pouring forth liberally : extravagant"},
                {"stomacher","noun","the center front section of a waist embroidery"},
                {"obligated","verb","to bind legally or morally : constrain"},
                {"verbosity","adjective","containing more words than necessary : wordy"},
                {"jockstrap","noun","athletic supporter"},
                {"heartsick","adjective","very despondent : depressed"},
                {"reactions","noun","the act or process or an instance of reacting"},
                {"humpbacks","noun","a humped or crooked back"},
                {"judgeship","noun","one who makes judgements: such as"},
                {"formulate","verb","devise"},
                {"oligarchy","noun","a group exercising such control "},
                {"frowziest","adjective","musty, stale"},
                {"insurable","adjective","that may be insured"},
                {"genocidal","noun","the deliberate and systematic destruction of a racial, political, or cultural group"},
                {"biathlons","noun","a composite athletic contest consisting of cross-country skiing and rifle sharpshooting"},
                {"staunched","verb","to stop the flow of blood from (a wound)"},
                {"manifesto","noun","to issue a manifesto"},
                {"raunchily","adjective","slovenly, dirty"},
                {"interplay","noun","interaction"},
                {"sectional","adjective","of or relating to a section"},
                {"prudently","adjective","characterized by, arising from, or showing prudence: such as"},
                {"absurdity","noun","the quality or state of being absurd: absurdness"},
                {"sulphated","noun","a salt or ester of sulfuric acid"},
                {"merchants","noun","a buyer and seller of commodities for profit : trader"},
                {"dominates","verb","rule, control"},
                {"ideograph","noun","ideogram"},
                {"downtimes","noun","time during which production is stopped"},
                {"dropsical","adjective","turgid, swollen"},
                {"cymbalist","noun","a person who plays the cymbals (a musical instrument)"},
                {"vectorial","noun","a quantity that has magnitude and direction "},
                {"particles","noun","a minute quantity or fragment"},
                {"quantizer","verb","to subdivide (something, such as energy) into small but measurable increments"},
                {"bulkheads","noun","an upright partition separating compartments"},
                {"ironclads","adjective","so firm or secure as to be unbreakable: such as"},
                {"housemaid","noun","a girl or woman who is a servant employed to do housework"},
                {"fumigated","verb","to apply smoke, vapor, or gas"},
                {"browniest","adjective","of the color brown"},
                {"headstock","noun","a bearing or pedestal for a revolving or moving part"},
                {"throwback","noun","reversion to an earlier type or phase : atavism"},
                {"nervously","adjective","sinewy, strong"},
                {"baronetcy","noun","the rank of a baronet"},
                {"furtively","adjective","done in a quiet and secretive way to avoid being noticed : surreptitious"},
                {"unfrocked","verb","defrock"},
                {"porcelain","noun","soft-paste porcelain"},
                {"polyhedra","noun","a solid formed by plane faces"},
                {"flashcube","noun","a cubical device incorporating four flashbulbs"},
                {"terminals","adjective","leading ultimately to death : fatal"},
                {"roguishly","noun","vagrant, tramp"},
                {"lucrative","adjective","producing wealth: profitable"},
                {"coastline","noun","a line that forms the boundary between the land and the ocean or a lake"},
                {"uniformed","adjective","of the same form with others : conforming to one rule or mode : consonant"},
                {"manicures","noun","manicurist"},
                {"bulwarked","noun","a solid wall-like structure raised for defense : rampart"},
                {"suctioned","noun","the act or process of sucking"},
                {"downstage","adverb or adjective","toward or at the front of a theatrical stage"},
                {"cauldrons","noun","a large kettle or boiler"},
                {"computers","noun","one that computes"},
                {"markdowns","noun","a lowering of price"},
                {"confiders","verb","to have confidence: trust"},
                {"symbolize","verb","to serve as a symbol of"},
                {"unclaimed","adjective","not claimed"},
                {"demijohns","noun","a large narrow-necked bottle usually enclosed in wickerwork"},
                {"incubates","verb","to sit on (eggs) so as to hatch by the warmth of the body"},
                {"obscurity","noun","the state of being difficult to see or understand"},
                {"foundries","noun","an establishment where founding is carried on"},
                {"watchdogs","noun","a dog kept to guard property"},
                {"truancies","noun","an act or instance of playing truant: the state of being truant"},
                {"signboard","noun","a board bearing a notice or sign"},
                {"comprised","verb","compose, constitute"},
                {"refashion","verb","remake, alter"},
                {"incubated","verb","to sit on (eggs) so as to hatch by the warmth of the body"},
                {"flyweight","noun","a boxer in a weight division having a maximum limit of 112 pounds — compare bantamweight"},
                {"chipboard","noun","a cardboard usually made entirely from waste paper"},
                {"yardstick","noun","a graduated measuring stick three feet (0.9144 meter) long"},
                {"disembark","verb","to remove to shore from a ship"},
                {"sequacity","adjective","subservient, tractable"},
                {"gumptions","noun","common sense, horse sense"},
                {"compendia","noun","a brief summary of a larger work or of a field of knowledge : abstract"},
                {"boulevard","noun","a broad often landscaped thoroughfare"},
                {"schnitzel","noun","a seasoned and garnished veal cutlet"},
                {"phonetics","noun","the system of speech sounds of a language or group of languages"},
                {"crankiest","adjective","given to fretful fussiness : easily angered"},
                {"relations","noun","the act of telling or recounting : account"},
                {"naughtier","adjective","vicious in moral character : wicked"},
                {"construed","verb","to construe a sentence or sentence part especially in connection with translating"},
                {"outbreaks","noun","insurrection, revolt"},
                {"wonderful","adjective","exciting wonder: marvelous, astonishing"},
                {"kilobytes","noun","a unit of computer information equal to 1024 bytes"},
                {"overplays","verb","to present (a dramatic role) extravagantly : exaggerate"},
                {"cloudiest","adjective","uncertain as to fact or outcome "},
                {"voyeurism","noun","the desires or behavior of a voyeur: such as"},
                {"ablutions","noun","a building on a military base that houses bathing and toilet facilities"},
                {"meltdowns","noun","the accidental melting of the core of a nuclear reactor"},
                {"centroids","noun","center of mass"},
                {"grumpiest","adjective","moodily cross : surly"},
                {"geraniums","noun","pelargonium"},
                {"paunchier","adjective","having a pot-belly"},
                {"sketchily","adjective","of the nature of a sketch: roughly outlined"},
                {"howitzers","noun","a short cannon used to fire projectiles"},
                {"nectarous","noun","the drink of the Greek and Roman gods"},
                {"carbonize","verb","to convert into carbon or a carbonic residue"},
                {"boyfriend","noun","a male friend"},
                {"publicans","noun","a Jewish tax collector for the ancient Romans"},
                {"hypocaust","noun","an ancient Roman central heating system with underground furnace"},
                {"worktable","noun","a table for holding working materials and implements"},
                {"curatives","adjective","relating to or used in the cure of diseases : tending to cure"},
                {"megaliths","noun","a very large usually rough stone used in prehistoric cultures as a monument or building block"},
                {"abolisher","verb","one who ends the observance or effect of something, such as a law"},
                {"obfuscate","verb","to throw into shadow : darken"},
                {"polarizes","verb","to give physical polarity to"},
                {"buckramed","noun","a stiff-finished heavily sized fabric of cotton or linen"},
                {"amplitude","noun","the extent or range of a quality, property, process, or phenomenon: such as"},
                {"abolished","verb","to end the observance or effect of something, such as a law"},
                {"pulsation","noun","rhythmical throbbing or vibrating (as of an artery)"},
                {"proactive","adjective","acting in anticipation of future problems, needs, or changes"},
                {"published","verb","to make generally known"},
                {"vasectomy","noun","surgical division or resection of all or part of the vas deferens usually to induce sterility"},
                {"reflation","noun","restoration of deflated prices to a desirable level"},
                {"hairstyle","noun","hairdo"},
                {"outwardly","adverb","on the outside : externally"},
                {"cytoplasm","noun","the organized complex organic substances external to the nuclear membrane of a cell"},
                {"alongside","adverb","along the side : in parallel position"},
                {"greyhound","noun","any of a breed of tall slender graceful smooth-coated dogs"},
                {"romanized","verb","to make Roman in character"},
                {"uncloaked","verb","to remove a cloak or cover from"},
                {"pandemics","adjective","an outbreak of a disease"},
                {"lunchtime","noun","the time at which lunch is usually eaten : noon"},
                {"conjugate","adjective","joined together especially in pairs : coupled"},
                {"stomached","noun","the part of the body that contains the stomach : belly, abdomen"},
                {"shipboard","noun","the side of a ship"},
                {"cenotaphs","noun","a tomb or a monument erected in honor of a person"},
                {"goldsmith","noun","one who makes or deals in articles of gold"},
                {"documents","noun","proof, evidence"},
                {"dynamites","noun","an explosive that is made of nitroglycerin"},
                {"rhapsodic","adjective","extravagantly emotional : rapturous"},
                {"veritably","adjective","actual, true"},
                {"pathogens","noun","a specific causative agent (such as a bacterium or virus) of disease"},
                {"hypnotics","adjective","tending to produce sleep : soporific"},
                {"sprinkled","verb","to scatter in drops or particles"},
                {"butcherly","adjective","resembling a butcher: savage"},
                {"mechanist","noun","mechanic"},
                {"heliports","noun","a landing and take-off place for a helicopter"},
                {"workmates","noun","a fellow worker"},
                {"garlicked","adjective","containing or prepared with garlic"},
                {"pinafores","noun","a sleeveless usually low-necked garment fastened in the back and worn as an apron or dress"},
                {"snowflake","noun","a flake or crystal of snow"},
                {"frolicked","adjective","full of fun : merry"},
                {"doctrines","noun","teaching, instruction"},
                {"insulated","verb","to place in a detached situation : isolate"},
                {"reducibly","verb","to draw together or cause to converge : consolidate"},
                {"godfather","noun","a man who sponsors a person at baptism"},
                {"moralized","verb","to explain or interpret morally"},
                {"veronicas","noun","any flower of a genus Veronica"},
                {"customize","verb","to build, fit, or alter according to individual specifications"},
                {"monastery","noun","a house for persons under religious vows"},
                {"unlatches","verb","to open or loose by lifting the latch"},
                {"punchiest","adjective","having punch: forceful, spirited"},
                {"townscape","noun","a representation of an urban scene"},
                {"pervasion","noun","the action of pervading or condition of being pervaded"},
                {"hypnotize","verb","to induce hypnosis in"},
                {"ordinates","noun","the Cartesian coordinate obtained by measuring parallel to the y-axis — compare abscissa"},
                {"diathermy","noun","the generation of heat in tissue by electric currents for medical or surgical purposes"},
                {"shipowner","noun","the owner of a ship"},
                {"frangible","adjective","readily or easily broken"},
                {"downbeats","noun","the downward stroke of a conductor to indicate a measure of music"},
                {"archdukes","noun","a sovereign prince"},
                {"kilohertz","noun","1000 hertz"},
                {"hypocrite","noun","a person who puts on a false appearance of virtue or religion"},
                {"gladsomer","adjective","giving or showing joy : cheerful"},
                {"congruity","noun","the quality or state of being congruent or congruous"},
                {"countably","adjective","capable of being counted"},
                {"hectogram","noun","a unit of mass equal to 100 grams — see Metric System Table"},
                {"cushioned","noun","a soft pillow or pad usually used for sitting, reclining, or kneeling"},
                {"countable","adjective","capable of being counted"},
                {"outflanks","verb","to get around the flank of (an opposing force)"},
                {"falconers","noun","a person who breeds, trains, or hunts with hawks"},
                {"playgoers","noun","a person who frequently attends plays"},
                {"heptagons","noun","a polygon of seven angles and seven sides"},
                {"anorexics","adjective","anorectic"},
                {"definably","adjective","able to be defined"},
                {"downscale","verb","lower in class, income, or quality"},
                {"flagstone","noun","flagentry"},
                {"bluepoint","noun","a small oyster (Crassostrea virginica) typically from the south shore of Long Island"},
                {"longevity","noun","long continuance : permanence, durability"},
                {"defoliant","noun","a chemical spray or dust applied to plants in order to cause the leaves to drop off prematurely"},
                {"zwiebacks","noun","a usually sweetened bread enriched with eggs"},
                {"democrats","noun","an adherent of democracy"},
                {"charioted","noun","a light four-wheeled pleasure or state carriage"},
                {"sidetrack","noun","siding sense"},
                {"parsimony","noun","the quality of being careful with money or resources : thrift"},
                {"outranked","verb","to rank higher than"},
                {"antiserum","noun","a serum containing antibodies"},
                {"burnished","verb","polish sense"},
                {"copyright","noun","the legal right of ownership of a creative work"},
                {"synodical","adjective","of or relating to a synod: synodal"},
                {"symphonic","adjective","harmonious, symphonious"},
                {"tramlines","noun","a streetcar line"},
                {"gridlocks","noun","traffic jams"},
                {"universal","adjective","applicable everywhere or in all cases"},
                {"contumely","noun","harsh language or treatment arising from haughtiness and contempt"},
                {"brimstone","noun","sulfur"},
                {"tapeworms","noun","a worm with a long flat body that lives as a parasite in the intestines of people and animals"},
                {"trapezoid","noun","a quadrilateral having only two sides parallel"},
                {"anthropic","adjective","of or relating to human beings or the period of their existence on earth"},
                {"eruptions","noun","an act, process, or instance of erupting"},
                {"admixture","noun","the action of mixing"},
                {"cautioned","noun","warning, admonishment"},
                {"mucilages","noun","a gelatinous substance of various plants"},
                {"inchworms","noun","looper sense"},
                {"chiefdoms","adjective","chiefly"},
                {"trapezium","noun","a quadrilateral with no parallel sides"},
                {"jubilates","verb","rejoice"},
                {"custodian","noun","one that guards and protects or maintains"},
                {"custodial","adjective","relating to guardianship"},
                {"forelimbs","noun","an arm, fin, wing, or leg that is located toward the front of the body"},
                {"balconies","noun","a platform that projects from the wall of a building and is enclosed by a parapet or railing"},
                {"convulsed","verb","to shake or agitate violently"},
                {"vulgarism","noun","vulgarity"},
                {"jubilated","verb","rejoice"},
                {"pharynges","noun","the muscular tubular passage of the vertebrate digestive and respiratory tracts"},
                {"polarized","verb","to give physical polarity to"},
                {"unearthly","adjective","not earthly: such as"},
                {"winsomely","adjective","cheerful, light-hearted"},
                {"balconied","noun","a platform that projects from the wall of a building and is enclosed by a parapet or railing"},
                {"revulsion","noun","a strong pulling or drawing away : withdrawal"},
                {"secondary","adjective","of second rank, importance, or value"},
                {"handspike","noun","a bar used as a lever"},
                {"mavericks","noun","an unbranded range animal"},
                {"vermouths","noun","a dry or sweet aperitif wine flavored with aromatic herbs and often used in mixed drinks"},
                {"countries","noun","an indefinite usually extended expanse of land : region"},
                {"legionary","adjective","of, relating to, or constituting a legion"},
                {"unlimbers","verb","to prepare something for action"},
                {"anxiously","adjective","characterized by extreme uneasiness of mind"},
                {"voyageurs","noun","a person who is an expert woodsman, boatman, and guide in remote regions"},
                {"phonemics","noun","a branch of linguistic analysis involving the study of phonemes"},
                {"intervals","noun","a space of time between events or states"},
                {"youngster","noun","a young person : youth"},
                {"plectrums","noun","pickentry"},
                {"embryonic","adjective","of or relating to an embryo"},
                {"larcenist","noun","a person who commits larceny"},
                {"goldfinch","noun","any of several small, active, often brightly-colored finches"},
                {"incurably","adjective","not likely to be changed or corrected "},
                {"workbench","noun","a bench on which work especially of mechanics, machinists, and carpenters is performed"},
                {"pneumatic","adjective","of, relating to, or using gas (such as air or wind):"},
                {"miserably","adjective","wretchedly inadequate or meager"},
                {"penumbras","noun","a space between the perfect shadow and the full light : an eclipse"},
                {"excusably","verb","to make apology for"},
                {"subatomic","adjective","of or relating to the inside of the atom"},
                {"mawkishly","adjective","lacking flavor or having an unpleasant taste"},
                {"glamoured","noun","alluring or fascinating attraction "},
                {"driveways","noun","a private road giving access from a public way to a building on abutting grounds"},
                {"tribesman","noun","a member of a tribe"},
                {"cyberpunk","noun","science fiction dealing with future urban societies dominated by computer technology"},
                {"mediators","noun","one that mediates"},
                {"underlays","verb","to cover, line, or traverse the bottom of : give support to on the underside or below"},
                {"incurable","adjective","not likely to be changed or corrected "},
                {"foresight","noun","an act or the power of foreseeing: prescience"},
                {"bifurcate","verb","to divide into two branches or parts"},
                {"jaundices","noun","yellowish pigmentation of the skin and body fluids due to sickness"},
                {"basketful","noun","as much or as many as a basket will hold"},
                {"nightmare","noun","an evil spirit formerly thought to oppress people during sleep"},
                {"southward","adverb or adjective","toward the south"},
                {"chantries","noun","an endowment for the chanting of masses commonly for the founder"},
                {"chipmunks","noun","any of a genus (Tamias) of small striped North American and Asian rodents"},
                {"philander","verb","to have casual or illicit sex with a person or with many people"},
                {"tediously","adjective","tiresome because of length or dullness : boring"},
                {"supernova","noun","the explosion of a star"},
                {"lethargic","adjective","laziness or lack of energy"},
                {"discovery","noun","disclosure"},
                {"frugality","noun","the quality or state of being frugal : thrifty"},
                {"graticule","noun","reticle"},
                {"triangles","noun","a polygon having three sides — compare spherical triangle"},
                {"mayflower","noun","any of various spring-blooming plants"},
                {"masterful","adjective","inclined and usually competent to act as master"},
                {"rudiments","noun","something unformed or undeveloped : beginning"},
                {"pugnacity","adjective","having a quarrelsome or combative nature : truculent"},
                {"printable","adjective","capable of being printed or of being printed from"},
                {"decathlon","noun","a 10-event athletic contest"},
                {"organdies","noun","a very fine transparent muslin with a stiff finish"},
                {"franchise","noun","freedom or immunity from some burden or restriction vested in a person or group"},
                {"neurotics","adjective","of, relating to, constituting, or affected with neurosis (see neurosis)"},
                {"simpleton","noun","a person lacking in common sense"},
                {"antipodes","noun","the exact opposite or contrary"},
                {"sunbather","verb","to take a sunbath"},
                {"profanity","noun","the quality or state of being profane"},
                {"observant","adjective","paying strict attention : watchful"},
                {"amortized","verb","to reduce (an amount) gradually: as"},
                {"ligaments","noun","the tissue connecting the extremities of bones or organs"},
                {"columnist","noun","one who writes a newspaper or magazine column"},
                {"workplace","noun","a place (such as a shop or factory) where work is done"},
                {"sunbathed","verb","to take a sunbath"},
                {"wristband","noun","the part of a sleeve covering the wrist"},
                {"dislocate","verb","to put out of place"},
                {"magnetics","adjective","of or relating to a magnet or to magnetism"},
                {"fractious","adjective","tending to be troublesome : unruly"},
                {"awestruck","adjective","filled with awe"},
                {"vibrantly","adjective","oscillating or pulsating rapidly"},
                {"diplomats","noun","a person whose work is keeping good relations between the governments of different countries"},
                {"budgetary","noun","a usually leather pouch, wallet, or pack"},
                {"outlander","noun","a person who belongs to another region, culture, or group : foreigner, stranger"},
                {"forehands","noun","superior position : advantage"},
                {"injectors","verb","to force a fluid (as a medicine) into by using a special needle"},
                {"bigmouths","noun","any of various fishes having noticeably large mouths: such as"},
                {"piquantly","adjective","engagingly provocative"},
                {"cabinetry","noun","cabinetwork"},
                {"chalkiest","noun","a soft white, gray, or buff limestone composed chiefly of the shells of foraminifers"},
                {"factorize","noun","the operation of resolving a quantity into factors"},
                {"ponytails","noun","a hairstyle in which the hair is pulled together and banded"},
                {"faculties","noun","ability, power: such as"},
                {"godparent","noun","a sponsor at baptism"},
                {"pulmonary","adjective","pulmonate"},
                {"roundelay","noun","a simple song with a refrain"},
                {"mousetrap","noun","a trap for mice"},
                {"vestryman","noun","a member of a vestry"},
                {"shortcake","noun","a crisp and often unsweetened biscuit or cookie"},
                {"provinces","noun","a country or region brought under the control of the ancient Roman government"},
                {"ideograms","noun","symbol used to represent an idea"},
                {"signatory","noun","a government bound with others by a signed convention"},
                {"romanizes","verb","to make Roman in character"},
                {"undercoat","noun","a coat or jacket worn under another"},
                {"submarine","adjective","underwater"},
                {"monthlies","noun","a monthly periodical"},
                {"newsgroup","noun","an electronic message board on the Internet that is devoted to a particular topic"},
                {"practised","verb","carry out, apply"},
                {"eightfold","adjective","having eight units or members"},
                {"ignorable","verb","to refuse to take notice of"},
                {"strangled","verb","to choke to death by compressing the throat with something (such as a hand or rope) : throttle"},
                {"harmonics","adjective","musical"},
                {"fumaroles","noun","a hole in a volcanic region from which hot gases and vapors issue"},
                {"publisher","noun","one that publishes something"},
                {"doughtier","adjective","marked by fearless resolution : valiant"},
                {"mosaicked","noun","a surface decoration made by inlaying pieces of variously colored material"},
                {"layperson","noun","a member of the laity"},
                {"polymaths","noun","a person of encyclopedic learning"},
                {"hymnaries","noun","hymnal"},
                {"crawliest","adjective","creepy-sense"},
                {"spearmint","noun","a common mint (Mentha spicata) grown for flavoring and especially for its aromatic oil"},
                {"hijackers","verb","to steal by stopping a vehicle on the highway"},
                {"gunpowder","noun","an explosive mixture of potassium nitrate, charcoal, and sulfur used in gunnery and blasting"},
                {"consulate","noun","a government by consuls"},
                {"manifolds","adjective","many"},
                {"blackouts","noun","a turning off of the stage lighting to separate scenes in a play or end a play or skit"},
                {"misquoted","noun","an act or instance of quoting something incorrectly : misquotation"},
                {"lawgivers","noun","one who gives a code of laws to a people"},
                {"chunkiest","adjective","stocky"},
                {"redaction","noun","an act or instance of redacting something"},
                {"outspread","verb","to spread out"},
                {"obscurely","adjective","dark, dim"},
                {"fornicate","verb","to commit fornication"},
                {"pitchfork","noun","a long-handled fork that has two or three long somewhat curved prongs"},
                {"sexuality","noun","the quality or state of being sexual:"},
                {"bachelors","noun","a young knight who follows the banner of another"},
                {"vaporized","verb","to convert (as by the application of heat or by spraying) into vapor"},
                {"eastbound","adjective","traveling or heading east"},
                {"intercoms","noun","a two-way communication system with a microphone and loudspeaker"},
                {"galumphed","verb","to move with a clumsy heavy tread"},
                {"urbanites","noun","a person who lives in a city"},
                {"sobriquet","noun","a descriptive name or epithet : nickname"},
                {"bigotedly","noun","a person who is obstinately or intolerantly devoted to his or her own opinions and prejudices"},
                {"homelands","noun","native land : fatherland"},
                {"subnormal","adjective","lower or smaller than normal"},
                {"vulcanize","verb","to subject to vulcanization"},
                {"stockyard","noun","a yard for stock"},
                {"bludgeons","noun","a short stick that usually has one thick or loaded end and is used as a weapon"},
                {"fulminate","verb","an often explosive salt (such as mercury fulminate) containing the group −CNO"},
                {"obtrusive","adjective","thrust out : protruding"},
                {"locksmith","noun","a person who makes or repairs locks"},
                {"parboiled","verb","to boil briefly as a preliminary or incomplete cooking procedure"},
                {"idolaters","noun","a worshipper of idols"},
                {"croakiest","verb","to make a deep harsh sound"},
                {"inspector","noun","a person employed to inspect something"},
                {"sublimate","verb","sublime sense"},
                {"cavernous","adjective","having caverns or cavities"},
                {"palmistry","noun","the art or practice of reading a person's character or future from the lines on the palms"},
                {"autopsied","noun","a critical examination, evaluation, or assessment of someone or something past"},
                {"confirmed","adjective","having received the rite of confirmation"},
                {"pomanders","noun","a mixture of aromatic substances enclosed in a perforated bag"},
                {"censorial","noun","a person who supervises conduct and morals: such as"},
                {"makeshift","noun","a usually crude and temporary expedient: substitute"},
                {"harmonies","noun","tuneful sound : melody"},
                {"princedom","noun","the jurisdiction, sovereignty, rank, or estate of a prince"},
                {"arguments","noun","the act or process of arguing, reasoning, or discussing : argumentation"},
                {"taxidermy","noun","the art of preparing, stuffing, and mounting the skins of animals and especially vertebrates"},
                {"captioned","noun","a title or explanation for a picture or illustration"},
                {"wordplays","noun","playful use of words: verbal wit"},
                {"daughters","noun","a female offspring especially of human parents"},
                {"capsulize","verb","capsule"},
                {"breakdown","noun","the action or result of breaking down: such as"},
                {"frontages","noun","a piece of land that lies adjacent (as to a street or the ocean)"},
                {"peculator","verb","embezzle"},
                {"vexations","noun","the quality or state of being vexed : irritation"},
                {"deformity","noun","the state of being deformed"},
                {"lifeworks","noun","the entire or principal work of one's lifetime"},
                {"fecundity","adjective","fruitful in offspring or vegetation : prolific"},
                {"ownership","noun","the state, relation, or fact of being an owner"},
                {"anhydrous","adjective","free from water and especially water of crystallization"},
                {"metalwork","noun","the product of metalworking"},
                {"expiatory","adjective","serving to expiate"},
                {"blowziest","adjective","having a sloppy or unkempt appearance or aspect : frowsy"},
                {"amortizes","verb","to reduce (an amount) gradually: as"},
                {"solemnity","noun","formal or ceremonious observance of an occasion or event"},
                {"patchwork","noun","something composed of miscellaneous or incongruous parts : hodgepodge"},
                {"brutishly","adjective","being unfeeling and stupid"},
                {"stridency","noun","the quality or state of being strident"},
                {"longhairs","noun","an impractical intellectual"},
                {"vocalizer","verb","to give voice to : utter"},
                {"turbofans","noun","a fan that is directly connected to a turbine"},
                {"imputable","verb","to credit or ascribe (something) to a person or a cause : attribute"},
                {"hydration","noun","a compound formed by the union of water with some other substance"},
                {"machinery","noun","machines in general or as a functioning unit"},
                {"fluorites","noun","a transparent or translucent mineral of different colors"},
                {"simulated","adjective","made to look genuine : fake"},
                {"verdantly","adjective","green in tint or color"},
                {"chemistry","noun","a science that deals with the composition, structure, and properties of substances"},
                {"spherical","adjective","having the form of a sphere or of one of its segments"},
                {"doctrinal","adjective","of, relating to, or preoccupied with doctrine"},
                {"routinely","noun","a theatrical number"},
                {"livestock","noun","animals kept or raised for use or pleasure"},
                {"gourmands","noun","one who is excessively fond of eating and drinking"},
                {"gyrations","noun","an act or instance of gyrating"},
                {"subjoined","verb","annex, append"},
                {"reputably","adjective","enjoying good repute: held in esteem"},
                {"fanlights","noun","a semicircular window with radiating bars"},
                {"givebacks","noun","a previous gain given back to management by workers"},
                {"parchment","noun","the skin of a sheep or goat prepared for writing on"},
                {"pegboards","noun","material (such as fiber board) with regularly spaced perforations"},
                {"combusted","verb","burn"},
                {"dialogues","noun","a written composition in which two or more characters are represented as conversing"},
                {"clergyman","noun","a member of the clergy"},
                {"sunflower","noun","any flower of a genus (Helianthus, especially H. annuus)"},
                {"laughters","noun","a sound of or as if of laughing"},
                {"pictogram","noun","pictograph"},
                {"guidepost","noun","indication, sign"},
                {"daylights","noun","the light of day"},
                {"mountable","noun","a high hill : mountain"},
                {"depravity","noun","the quality or state of being depraved"},
                {"harmonize","verb","to play or sing in harmony"},
                {"flowchart","noun","a diagram that shows a step-by-step progression"},
                {"righteous","adjective","acting in accord with divine or moral law : free from guilt or sin"},
                {"scoundrel","noun","a disreputable person : rascal"},
                {"fancywork","noun","decorative needlework"},
                {"crushable","verb","hug, embrace"},
                {"complaint","noun","an expression of discontent, regret, pain, censure, resentment, or grief"},
                {"cuneiform","adjective","having the shape of a wedge"},
                {"flouncier","verb","to move so as to draw attention to oneself "},
                {"complains","verb","to express grief, pain, or discontent : find fault"},
                {"bastioned","noun","stronghold sense"},
                {"headlocks","noun","a hold in which a wrestler encircles an opponent's head with one arm"},
                {"grapeshot","noun","an anti-personnel weapon consisting of a cluster of small iron balls shot from a cannon"},
                {"fieldwork","noun","a temporary fortification thrown up by an army in the field"},
                {"obscenity","noun","the quality or state of being obscene"},
                {"republics","noun","a government having a chief of state who is not a monarch"},
                {"yarmulkes","noun","a skullcap worn especially by Orthodox and Conservative Jewish males"},
                {"formulaic","noun","a set form of words for use in a ceremony or ritual"},
                {"graphites","noun","a soft black lustrous form of carbon that conducts electricity"},
                {"darkliest","adjective","arising from or showing evil traits or desires : evil"},
                {"blockages","noun","the action of blocking or the state of being blocked: as"},
                {"subfamily","noun","a category in biological classification ranking below a family and above a genus"},
                {"windbreak","noun","a growth of trees or shrubs serving to break the force of wind"},
                {"scrounged","verb","steal, swipe"},
                {"triumphal","noun","a victory or conquest by or as if by military force"},
                {"roughneck","noun","a rough or uncouth person"},
                {"zymurgies","noun","a branch of applied chemistry that deals with fermentation processes"},
                {"furbished","verb","to make lustrous : polish"},
                {"cretinous","noun","one afflicted with cretinism"},
                {"atomizers","noun","an instrument for atomizing usually a perfume, disinfectant, or medicament"},
                {"unsightly","adjective","not pleasant to look at : ugly"},
                {"integrals","adjective","essential to completeness : constituent"},
                {"angelfish","noun","brightly colored bony fishes (family Pomacanthidae) of warm seas"},
                {"adversity","noun","hard times : misfortune"},
                {"naughtily","adjective","vicious in moral character : wicked"},
                {"quicksand","noun","sand readily yielding to pressure"},
                {"obligates","verb","to bind legally or morally : constrain"},
                {"neuralgic","noun","acute paroxysmal pain radiating along the nerves"},
                {"starchily","adjective","formal, stiff"},
                {"metabolic","adjective","of, relating to, or based on metabolism"},
                {"stepchild","noun","a child of one's wife or husband by a former partner"},
                {"goldbrick","noun","a worthless brick that appears to be of gold"},
                {"ghostlike","noun","the seat of life or intelligence : soul"},
                {"interlock","verb","to become locked together or interconnected"},
                {"formative","adjective","giving or capable of giving form : constructive"},
                {"hungriest","adjective","feeling an uneasy or painful sensation from lack of food : feeling hunger"},
                {"abusively","adjective","characterized by wrong or improper use or action"},
                {"vocalizes","verb","to give voice to : utter"},
                {"triumphed","noun","a victory or conquest by or as if by military force"},
                {"ibuprofen","noun","a non-steroidal anti-inflammatory drug C13H18O2used to relieve pain and fever"},
                {"sprightly","adjective","marked by a gay lightness and vivacity : spirited"},
                {"blotchier","verb","to mark or mar with blotches"},
                {"eucalypti","noun","any of a genus (Eucalyptus) of mostly Australian evergreen trees"},
                {"plethoras","noun","overabundance; excess"},
                {"glamorize","verb","to look upon or depict as glamorous: romanticize"},
                {"chandlers","noun","a maker or seller of tallow or wax candles and usually soap"},
                {"hypnotism","noun","the study or act of inducing hypnosis— compare mesmerism"},
                {"slaughter","noun","the act of killing"},
                {"shakedown","noun","an improvised bed (such as one made up on the floor)"},
                {"thumbnail","noun","the nail of the thumb"},
                {"microwave","noun","a comparatively short electromagnetic wave"},
                {"prudishly","adjective","marked by prudery: priggish"},
                {"anguished","adjective","suffering anguish: tormented"},
                {"unshackle","verb","to free from shackles"},
                {"piteously","adjective","of a kind to move to pity or compassion"},
                {"croupiest","noun","the rump of a quadruped"},
                {"fluorines","noun","a pale yellowish flammable irritating toxic diatomic gas"},
                {"fragments","noun","to fall to pieces"},
                {"objurgate","noun","a harsh rebuke"},
                {"voluntary","adjective","proceeding from the will or from one's own choice or consent"},
                {"policeman","noun","a member of a police force"},
                {"deflation","noun","an act or instance of deflating: the state of being deflated"},
                {"uniformly","adjective","of the same form with others : conforming to one rule or mode : consonant"},
                {"combative","adjective","marked by eagerness to fight or contend"},
                {"clarinets","noun","a single-reed woodwind instrument having a cylindrical tube with a moderately flared bell"},
                {"spadework","noun","work done with a spade"},
                {"staunchly","adjective","watertight, sound"},
                {"uprightly","adjective","perpendicular, vertical"},
                {"seduction","noun","the act of seducing"},
                {"filaments","noun","a single thread or a thin flexible threadlike object, process, or appendage"},
                {"nightcaps","noun","a cloth cap worn with nightclothes"},
                {"lifeboats","noun","a sturdy buoyant boat used in emergency"},
                {"garnished","verb","decorate, embellish"},
                {"homewards","adverb","being or going in the direction of home"},
                {"jointures","noun","an act of joining: the state of being joined"},
                {"enzymatic","adjective","of, relating to, or produced by an enzyme"},
                {"shipwreck","noun","a wrecked ship or its parts"},
                {"moralizes","verb","to explain or interpret morally"},
                {"doughiest","adjective","resembling dough: such as"},
                {"lazybones","noun","a lazy person"},
                {"nightclub","noun","a place of entertainment open at night"},
                {"sycophant","noun","a servile self-seeking flatterer"},
                {"flatworms","noun","any worm of the phylum Platyhelminthes : platyhelminth"},
                {"repulsion","noun","the action of repulsing: the state of being repulsed"},
                {"abjection","noun","a low or downcast state : degradation"},
                {"snowdrift","noun","a bank of drifted snow"},
                {"hamstrung","noun","either of two groups of tendons at the back of the human knee"},
                {"emblazons","verb","to inscribe or adorn with or as if with heraldic bearings or devices"},
                {"metaphors","noun","a figure of speech"},
                {"misplaced","verb","mislay"},
                {"flamencos","noun","a vigorous rhythmic dance style of the Andalusian Gypsies"},
                {"clerkship","noun","cleric"},
                {"gymnastic","adjective","of or relating to gymnastics: athletic"},
                {"conflated","verb","to bring together : fuse"},
                {"cornstalk","noun","a stalk of corn"},
                {"signature","noun","the act of signing one's name to something"},
                {"conflates","verb","to bring together : fuse"},
                {"ghastlier","adjective","terrifyingly horrible to the senses : frightening"},
                {"ruminates","verb","to go over in the mind repeatedly and often casually or slowly"},
                {"purloined","verb","to appropriate wrongfully and often by a breach of trust"},
                {"claymores","noun","a large 2-edged sword formerly used by Scottish Highlanders"},
                {"reclusion","noun","the state of being recluse"},
                {"backdrops","noun","a painted cloth hung across the rear of a stage"},
                {"birdhouse","noun","an artificial nesting site for birds"},
                {"strangely","adjective","of, relating to, or characteristic of another country : foreign"},
                {"cursively","adjective","running, coursing: such as"},
                {"herbalist","noun","a person who practices healing by the use of herbs"},
                {"exactions","noun","the act or process of exacting"},
                {"vouchsafe","verb","to grant or furnish often in a gracious or condescending manner"},
                {"gyrfalcon","noun","an arctic falcon (Falco rusticolus)"},
                {"simulator","noun","one that simulates"},
                {"reduction","noun","the act or process of reducing: the state of being reduced"},
                {"normality","adjective","having a concentration of one gram equivalent of soluteper liter"},
                {"macintosh","noun","raincoat"},
                {"compliant","adjective","ready or disposed to comply: submissive"},
                {"operantly","adjective","functioning or tending to produce effects : effective"},
                {"mishandle","verb","to treat roughly : maltreat"},
                {"drumstick","noun","a stick for beating a drum"},
                {"blueprint","noun","a detailed outline or plan of action"},
                {"royalties","noun","royal status or power : sovereignty"},
                {"uncharted","adjective","unknown"},
                {"upholders","verb","to give support to"},
                {"cankerous","noun","an erosive or spreading sore"},
                {"bohemians","noun","a native or inhabitant of Bohemia"},
                {"westbound","adjective","traveling or heading west"},
                {"orientals","adjective","of, relating to, or situated in the orient"},
                {"histogram","noun","a representation of a frequency distribution"},
                {"clampdown","noun","to impose restrictions : crack down"},
                {"overhangs","verb","to project over"},
                {"veracious","adjective","truthful, honest"},
                {"hesitancy","noun","the quality or state of being hesitant: such as"},
                {"curbstone","noun","a stone or edging of concrete forming a curb"},
                {"lifeguard","noun","a usually expert swimmer employed (as at a beach or a pool) to safeguard other swimmers"},
                {"impugners","verb","assail"},
                {"nursemaid","noun","a girl or woman who is regularly employed to look after children"},
                {"cylinders","noun","any cylinder-like object or part, whether solid or hollow"},
                {"incubator","noun","one that incubates: such as"},
                {"dangerous","adjective","deadly"},
                {"backfires","verb","to make or undergo a backfire"},
                {"grubstake","noun","supplies or funds furnished a mining prospector on promise of a share in his discoveries"},
                {"costively","adjective","affected with constipation"},
                {"dovetails","noun","something resembling a dove's tail"},
                {"anchovies","noun","any of a family (Engraulidae) of small fishes"},
                {"charwomen","noun","a cleaning woman especially in a large building"},
                {"ruminated","verb","to go over in the mind repeatedly and often casually or slowly"},
                {"backfired","verb","to make or undergo a backfire"},
                {"fashioner","noun","kind, sort"},
                {"menstrual","adjective","of or relating to menstruation"},
                {"formalist","noun","one strictly adheres to a tradition, religion or philosophy"},
                {"consulter","verb","to have regard to : consider"},
                {"constable","noun","a high officer of a royal court or noble household especially in the Middle Ages"},
                {"humanizer","verb","to represent as human: attribute human qualities to"},
                {"humanizes","verb","to represent as human: attribute human qualities to"},
                {"prodigals","adjective","characterized by profuse or wasteful expenditure : lavish"},
                {"panegyric","noun","formal or elaborate praise"},
                {"misplayed","noun","a wrong or unskillful play : error"},
                {"consulted","verb","to have regard to : consider"},
                {"whipcords","noun","a thin tough cord made of braided or twisted hemp or catgut"},
                {"tarnished","verb","to dull or destroy the luster of by or as if by air, dust, or dirt : soil, stain"},
                {"fashioned","noun","kind, sort"},
                {"shrinkage","noun","the act or process of shrinking"},
                {"gradients","noun","the rate of regular or graded ascent or descent"},
                {"education","noun","the action or process of educating or of being educated"},
                {"humanized","verb","to represent as human: attribute human qualities to"},
                {"profanely","verb","to treat (something sacred) with abuse, irreverence, or contempt : desecrate"},
                {"backfield","noun","the football players whose positions are behind the line of scrimmage"},
                {"poultices","noun","a medicated mass spread on cloth and applied to sores"},
                {"inductors","noun","one that inducts"},
                {"courtesan","noun","a prostitute with a courtly, wealthy, or upper-class clientele"},
                {"conspired","verb","plot, contrive"},
                {"handworks","noun","work done with the hands and not by machines : handiwork"},
                {"hazelnuts","noun","the brown nut of a hazel"},
                {"demoniacs","adjective","possessed or influenced by a demon"},
                {"binocular","adjective","of, relating to, using, or adapted to the use of both eyes"},
                {"scrambled","verb","to spread or grow irregularly : sprawl, straggle"},
                {"portables","adjective","bearable"},
                {"curtained","noun","a hanging screen usually capable of being drawn back or up"},
                {"kilograms","noun","the base unit of mass in the International System of Units"},
                {"ovenbirds","noun","any of small brown passerine birds (family Furnariidae)"},
                {"preflight","adjective","to inspect (an aircraft) before a flight"},
                {"probative","adjective","serving to test or try : exploratory"},
                {"formalize","verb","to give a certain or definite form to : shape"},
                {"upholster","verb","to furnish with or as if with upholstery"},
                {"crumbiest","adjective","crumbly"},
                {"vulgarize","verb","to diffuse generally : popularize"},
                {"undertows","noun","the current beneath the surface of open water"},
                {"pseudonym","noun","a fictitious name"},
                {"overhands","adjective","made with the hand brought forward and down from above shoulder level"},
                {"heinously","adjective","hatefully or shockingly evil : abominable"},
                {"ligatured","noun","something that is used to bind"},
                {"holidayer","noun","holy day"},
                {"focusable","noun","a point of concentration"},
                {"dismantle","verb","to destroy the integrity or functioning of "},
                {"southerly","adjective or adverb","a wind from the south"},
                {"lubricate","verb","to make smooth or slippery"},
                {"ligatures","noun","something that is used to bind"},
                {"afterglow","noun","a glow remaining where a light has disappeared"},
                {"brightens","verb","to become bright or brighter"},
                {"discharge","verb","to relieve of a charge, load, or burden:"},
                {"overbuilt","verb","to build beyond the actual demand of"},
                {"mouldiest","adjective","of, resembling, or covered with mold"},
                {"unclasped","verb","to loosen a hold"},
                {"algorithm","noun","a set of rules for solving a problem in a finite number of steps"},
                {"horseplay","noun","rough or boisterous play"},
                {"unscathed","adjective","wholly unharmed : not injured"},
                {"romantics","adjective","consisting of or resembling a romance"},
                {"bystander","noun","a person present or standing near but taking no part in what is going on"},
                {"stockpile","noun","a storage pile: such as"},
                {"firedamps","noun","a combustible mine gas that consists chiefly of methane"},
                {"proximate","adjective","very near : close"},
                {"ignoramus","noun","an utterly ignorant person : dunce"},
                {"manpowers","noun","power available from or supplied by the physical effort of human beings"},
                {"badmouths","verb","to criticize severely"},
                {"craftsmen","noun","a worker who practices a trade or handicraft"},
                {"drumbeats","noun","a stroke on a drum or its sound"}
        };

        for(int i = 0; i<nineList.length;i++){
            Board tempB = new Board(nineList[i][0],nineList[i][1],nineList[i][2],1, i);
            wordNine.add(tempB);
        }
    }
    private void initWordFour(){

    }

    public int getSmallFont() {
        return smallFont;
    }
    public int getMedFont() {
        return medFont;
    }
    public int getBoardFont() {
        return boardFont;
    }
    public int getBigFont() {
        return bigFont;
    }
    public int getPosTop() {
        return posTop;
    }
    public int getPosTopMid() {
        return posTopMid;
    }
    public int getPosMid() {
        return posMid;
    }
    public int getPosBotMid() {
        return posBotMid;
    }
    public int getPosBot() {
        return posBot;
    }
    public int getFasterText() {
        return fasterText;
    }
    public int getFastText() {
        return fastText;
    }
    public int getNormText() {
        return normText;
    }
    public int getSlowText() {
        return slowText;
    }
    public int getEASY_BOARD() {
        return EASY_BOARD;
    }
    public int getMED_BOARD() {
        return MED_BOARD;
    }
    public int getHARD_BOARD() {
        return HARD_BOARD;
    }
    public int getHIGHLIGHT_COLOR() {
        return HIGHLIGHT_COLOR;
    }
    public int getNEIGHBOR_COLOR() {
        return NEIGHBOR_COLOR;
    }
    public int getFIXED_COLOR() {
        return FIXED_COLOR;
    }
    public int getERROR_COLOR() {
        return ERROR_COLOR;
    }
    public int getBG_COLOR() {
        return BG_COLOR;
    }
    public int getREGULAR_COLOR() {
        return REGULAR_COLOR;
    }
    public int getFONT_COLOR() {
        return FONT_COLOR;
    }
    public int getSELECT_COLOR() {
        return SELECT_COLOR;
    }

    public ArrayList<Board> getWordNine() {
        return wordNine;
    }
    public ArrayList<Board> getWordFour() {
        return wordFour;
    }
}
